## traefik configuration
##

controller:
  name: controller
  image:
    repository: traefik
    tag: v1.5.3
    pullPolicy: IfNotPresent

  # How to deploy. Can either be "deployment" or "daemonset".
  # A deployment can be scaled while daemonset will install exactly 1 pod per node.
  deploy:
    type: deployment

  # Number of pods to create. Only makes sense if deploy type is "deployment".
  replicas: 3

  # Whether to listen on node IP or be assigned a pod IP
  # Listening on node would however, means that only one pod can be scheduled on a node.
  hostNetwork: false

service:
  # Valid types: ClusterIP, NodePort, LoadBalancer, ExternalName
  # https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services---service-types
  # With service type NodePort, a port is assigned on the nodes to listen to connections, and a cluster IP is also assigned
  serviceType: NodePort
