{{- if eq .Values.controller.deploy.type "daemonset" -}}
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: {{ template "traefik-ingress.name" . }}-controller
  namespace: kube-system
  labels:
    k8s-app: {{ template "traefik-ingress.name" . }}-lb
    app: {{ template "traefik-ingress.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  template:
    metadata:
      labels:
        k8s-app: {{ template "traefik-ingress.name" . }}-lb
        name: {{ template "traefik-ingress.name" . }}-lb
    spec:
      serviceAccountName: {{ template "traefik-ingress.name" . }}-controller
      terminationGracePeriodSeconds: 60
      hostNetwork: {{ .Values.controller.hostNetwork }}
      containers:
      - image: image: "{{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag }}"
        imagePullPolicy: "{{ .Values.controller.image.pullPolicy }}"
        name: {{ template "traefik-ingress.name" . }}-lb
        ports:
        - name: http
          containerPort: 80
          hostPort: 80
        - name: admin
          containerPort: 8080
        securityContext:
          privileged: true
        args:
        - -d
        - --api
        - --kubernetes
{{- end -}}
